#! /usr/bin/ruby
# __        ___           _ __        __        ___ ____        _
# \ \      / / |__   __ _| |\ \      / /_ _ ___|_ _|  _ \  ___ (_)_ __   __ _
#  \ \ /\ / /| '_ \ / _` | __\ \ /\ / / _` / __|| || | | |/ _ \| | '_ \ / _` |
#   \ V  V / | | | | (_| | |_ \ V  V / (_| \__ \| || |_| | (_) | | | | | (_| |
#    \_/\_/  |_| |_|\__,_|\__| \_/\_/ \__,_|___/___|____/ \___/|_|_| |_|\__, |
#                                                                       |___/
# Reminds you of that thing you should be doing, but you forgot.
#
# Usage:
# cmd: "doing something or another"
# > something or another
# cmd: "wwid"
# > something or another

FILE_NAME_TODO = "/var/tmp/.doing-#{File.basename(Dir.getwd)}"

def help
  puts <<-HEREDOC

wwid: what the hell was I doing

Its a todo list with one item. Set the todo with the `doing` command
and read it with the `wwid` (WhatWasIDoing) command

Looks like you weren't doing anything.
Set your todo with `doing [whatever you're doing]`

  HEREDOC
  exit
end

if not File.exist? FILE_NAME_TODO
  help
end

File.open(FILE_NAME_TODO, 'r') do |file|
  file.each_line do
    |line| puts line
  end
end
